### ISSUE TITLE
CBW: Switching River Arms while Conformance layer selected displays Depth surface and not Conformance

### ISSUE THREAD

**Issue by wongrm** [pwgsc/avadepth#10]
We should either reset the radio to bathymetry or display the conformance layer.

No need to action ATM.  May get the team to tackled this.

**Comment by wsidl** [comment]
Adding more context to this issue:

When the "Conformance" surface layer is selected and the user changes the river arm, the layer that appears after the river change completes is the "Bathymetry" surface and not "Conformance".

## Steps to Reproduce

Step 1 - Conformance layer selected:
![image](https://user-images.githubusercontent.com/6453466/144690164-f83fea3f-647d-4497-a06f-2c5ac96a44c7.png)

Step 2 - Change River Arms:
![image](https://user-images.githubusercontent.com/6453466/144690306-6343185d-8b40-448e-b7a6-925413668d99.png)

## Expected Results

The layer represented by the currently selected radio button should identify which layer of the new arm is to be displayed.

## Current Experience

The "Bathymetry" layer is always being displayed regardless of what is currently selected in the properties window.

![image](https://user-images.githubusercontent.com/6453466/144690452-6c1c6c5f-4f95-4ab4-8905-9f98a6fb2e28.png)

**Comment by wsidl** [comment]
@wongrm I pushed this change directly to master without knowing it. Instead of reverting it, can you please confirm the change suites the needs of this issue.

**Comment by wsidl** [comment]
Change made and deployed to production
