### ISSUE TITLE
Map focuses on incorrect location bounds for the Main Arm and Pitt River on Channel Bathymetry Web Map page

### ISSUE THREAD

**Issue by ljkirby** [pwgsc/avadepth#14]
**Problem**: The map on the Channel Bathymetry Webmap page (/avdpth_srch-eng.html?page=cbw) should automatically move to focus on the river selected in the map pane/legend. This functionality is broken for the Main Arm river and the Pitt River. 

**Steps to replicate**: 
1. Visit the Channel Bathymetry Webmap (/avdpth_srch-eng.html?page=cbw)
2. Toggle the river selection to either "Main Arm" or "Pitt River": 
![image](https://user-images.githubusercontent.com/22060917/147296230-953ee824-c531-4c46-af2b-9ef646a6402e.png)
3. See error --> Map does not move to focus on the selected river. It instead stays focused on the South Arm river. 

This is what you see: 

![image](https://user-images.githubusercontent.com/22060917/147296303-b2572b32-2397-4fe3-b621-46f0a8170ad2.png)

This is what it SHOULD look like instead: 

![image](https://user-images.githubusercontent.com/22060917/147296340-2e8b28ac-45c5-4015-bd09-0bf203c5789b.png)

**Comment by ljkirby** [comment]
@wongrm Issue appears to be related to incorrect bounds within the `RiverSections` object. The bounds for South Arm, Main Arm, and Pitt River are all set to the exact same coordinates: 

![image](https://user-images.githubusercontent.com/22060917/147296647-3aea9613-7445-463c-8ee8-c0593733944e.png)

Just need to figure out what the proper bounding coordinates are then will put in a PR with the corrections

**Comment by wsidl** [comment]
@ljkirby thanks for pointing this out.

When this part of the code was built, we had no data so I could only define bounds based on what I could determine (South Arm, North Arm). The other arms could have a lot of variability and couldn't define an extent for those.

**Comment by wsidl** [comment]
@wongrm this fix has been merged into the master branch and ready for deployment
